// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrsLVJT79AaC9QybGk1H9Y3bX7PgmxTvY',
    appId: '1:577546316492:web:4d1ecffc9430558394b069',
    messagingSenderId: '577546316492',
    projectId: 'kwentokape',
    authDomain: 'kwentokape.firebaseapp.com',
    databaseURL: 'https://kwentokape-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kwentokape.appspot.com',
    measurementId: 'G-NRDVXZCCC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKUX-5g4vUBftQk4fImnwpWRpSDe4nATU',
    appId: '1:577546316492:android:5e0c5dcb5243ff2794b069',
    messagingSenderId: '577546316492',
    projectId: 'kwentokape',
    databaseURL: 'https://kwentokape-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kwentokape.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsm8CXeDDwmH14dZakb_JmBbQ7zrJt5lg',
    appId: '1:577546316492:ios:80509be18002278394b069',
    messagingSenderId: '577546316492',
    projectId: 'kwentokape',
    databaseURL: 'https://kwentokape-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kwentokape.appspot.com',
    iosBundleId: 'com.example.kwentokape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsm8CXeDDwmH14dZakb_JmBbQ7zrJt5lg',
    appId: '1:577546316492:ios:72a2e101c86591ec94b069',
    messagingSenderId: '577546316492',
    projectId: 'kwentokape',
    databaseURL: 'https://kwentokape-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kwentokape.appspot.com',
    iosBundleId: 'com.example.kwentokape.RunnerTests',
  );
}
